touch library/arithmetic/matrix/ntm_matrix_arithmetic.java
touch library/arithmetic/scalar/ntm_scalar_arithmetic.java
touch library/arithmetic/tensor/ntm_tensor_arithmetic.java
touch library/arithmetic/test_scalar_arithmetic.java
touch library/arithmetic/vector/ntm_vector_arithmetic.java
touch library/math/algebra/matrix/ntm_matrix_algebra.java
touch library/math/algebra/scalar/ntm_scalar_algebra.java
touch library/math/algebra/tensor/ntm_tensor_algebra.java
touch library/math/algebra/vector/ntm_vector_algebra.java
touch library/math/calculus/matrix/ntm_matrix_calculus.java
touch library/math/calculus/tensor/ntm_tensor_calculus.java
touch library/math/calculus/vector/ntm_vector_calculus.java
touch library/math/function/matrix/ntm_matrix_function.java
touch library/math/function/scalar/ntm_scalar_function.java
touch library/math/function/vector/ntm_vector_function.java
touch library/math/statitics/matrix/ntm_matrix_statitics.java
touch library/math/statitics/scalar/ntm_scalar_statitics.java
touch library/math/statitics/vector/ntm_vector_statitics.java
touch library/nn/ANN/components/ntm_masked_multi_head_attention.java
touch library/nn/ANN/components/ntm_masked_scaled_dot_product_attention.java
touch library/nn/ANN/components/ntm_multi_head_attention.java
touch library/nn/ANN/components/ntm_scaled_dot_product_attention.java
touch library/nn/ANN/controller/fnn/ntm_fnn.java
touch library/nn/ANN/controller/lstm/ntm_lstm.java
touch library/nn/ANN/functions/ntm_layer_norm.java
touch library/nn/ANN/functions/ntm_positional_encoding.java
touch library/nn/ANN/inputs/ntm_inputs_vector.java
touch library/nn/ANN/inputs/ntm_keys_vector.java
touch library/nn/ANN/inputs/ntm_queries_vector.java
touch library/nn/ANN/inputs/ntm_values_vector.java
touch library/nn/ANN/top/ntm_controller.java
touch library/nn/ANN/top/ntm_decoder.java
touch library/nn/ANN/top/ntm_encoder.java
touch library/nn/DNC/memory/dnc_addressing.java
touch library/nn/DNC/memory/dnc_allocation_weighting.java
touch library/nn/DNC/memory/dnc_backward_weighting.java
touch library/nn/DNC/memory/dnc_forward_weighting.java
touch library/nn/DNC/memory/dnc_matrix_content_based_addressing.java
touch library/nn/DNC/memory/dnc_memory_matrix.java
touch library/nn/DNC/memory/dnc_memory_retention_vector.java
touch library/nn/DNC/memory/dnc_precedence_weighting.java
touch library/nn/DNC/memory/dnc_read_content_weighting.java
touch library/nn/DNC/memory/dnc_read_vectors.java
touch library/nn/DNC/memory/dnc_read_weighting.java
touch library/nn/DNC/memory/dnc_sort_vector.java
touch library/nn/DNC/memory/dnc_temporal_link_matrix.java
touch library/nn/DNC/memory/dnc_usage_vector.java
touch library/nn/DNC/memory/dnc_vector_content_based_addressing.java
touch library/nn/DNC/memory/dnc_write_content_weighting.java
touch library/nn/DNC/memory/dnc_write_weighting.java
touch library/nn/DNC/top/dnc_interface_matrix.java
touch library/nn/DNC/top/dnc_interface_top.java
touch library/nn/DNC/top/dnc_interface_vector.java
touch library/nn/DNC/top/dnc_output_vector.java
touch library/nn/DNC/top/dnc_top.java
touch library/nn/DNC/trained/dnc_trained_top.java
touch library/nn/FNN/convolutional/ntm_controller.java
touch library/nn/FNN/standard/ntm_controller.java
touch library/nn/LSTM/convolutional/ntm_activation_gate_vector.java
touch library/nn/LSTM/convolutional/ntm_controller.java
touch library/nn/LSTM/convolutional/ntm_forget_gate_vector.java
touch library/nn/LSTM/convolutional/ntm_hidden_gate_vector.java
touch library/nn/LSTM/convolutional/ntm_input_gate_vector.java
touch library/nn/LSTM/convolutional/ntm_output_gate_vector.java
touch library/nn/LSTM/convolutional/ntm_state_gate_vector.java
touch library/nn/LSTM/standard/ntm_activation_gate_vector.java
touch library/nn/LSTM/standard/ntm_controller.java
touch library/nn/LSTM/standard/ntm_forget_gate_vector.java
touch library/nn/LSTM/standard/ntm_hidden_gate_vector.java
touch library/nn/LSTM/standard/ntm_input_gate_vector.java
touch library/nn/LSTM/standard/ntm_output_gate_vector.java
touch library/nn/LSTM/standard/ntm_state_gate_vector.java
touch library/nn/NTM/memory/ntm_addressing.java
touch library/nn/NTM/memory/ntm_matrix_content_based_addressing.java
touch library/nn/NTM/memory/ntm_vector_content_based_addressing.java
touch library/nn/NTM/read_heads/ntm_reading.java
touch library/nn/NTM/top/ntm_interface_matrix.java
touch library/nn/NTM/top/ntm_interface_top.java
touch library/nn/NTM/top/ntm_interface_vector.java
touch library/nn/NTM/top/ntm_output_vector.java
touch library/nn/NTM/top/ntm_top.java
touch library/nn/NTM/trained/ntm_trained_top.java
touch library/nn/NTM/write_heads/ntm_erasing.java
touch library/nn/NTM/write_heads/ntm_writing.java
touch library/state/feedback/ntm_state_feedback.java
touch library/state/outputs/ntm_state_outputs.java
touch library/state/top/ntm_state_top.java
touch library/trainer/differentiation/ntm_matrix_controller_differentiation.java
touch library/trainer/differentiation/ntm_vector_controller_differentiation.java
touch library/trainer/FNN/ntm_fnn_b_trainer.java
touch library/trainer/FNN/ntm_fnn_d_trainer.java
touch library/trainer/FNN/ntm_fnn_k_trainer.java
touch library/trainer/FNN/ntm_fnn_trainer.java
touch library/trainer/FNN/ntm_fnn_u_trainer.java
touch library/trainer/FNN/ntm_fnn_v_trainer.java
touch library/trainer/FNN/ntm_fnn_w_trainer.java
touch library/trainer/LSTM/activation/ntm_lstm_activation_b_trainer.java
touch library/trainer/LSTM/activation/ntm_lstm_activation_d_trainer.java
touch library/trainer/LSTM/activation/ntm_lstm_activation_k_trainer.java
touch library/trainer/LSTM/activation/ntm_lstm_activation_trainer.java
touch library/trainer/LSTM/activation/ntm_lstm_activation_u_trainer.java
touch library/trainer/LSTM/activation/ntm_lstm_activation_v_trainer.java
touch library/trainer/LSTM/activation/ntm_lstm_activation_w_trainer.java
touch library/trainer/LSTM/forget/ntm_lstm_forget_b_trainer.java
touch library/trainer/LSTM/forget/ntm_lstm_forget_d_trainer.java
touch library/trainer/LSTM/forget/ntm_lstm_forget_k_trainer.java
touch library/trainer/LSTM/forget/ntm_lstm_forget_trainer.java
touch library/trainer/LSTM/forget/ntm_lstm_forget_u_trainer.java
touch library/trainer/LSTM/forget/ntm_lstm_forget_v_trainer.java
touch library/trainer/LSTM/forget/ntm_lstm_forget_w_trainer.java
touch library/trainer/LSTM/input/ntm_lstm_input_b_trainer.java
touch library/trainer/LSTM/input/ntm_lstm_input_d_trainer.java
touch library/trainer/LSTM/input/ntm_lstm_input_k_trainer.java
touch library/trainer/LSTM/input/ntm_lstm_input_trainer.java
touch library/trainer/LSTM/input/ntm_lstm_input_u_trainer.java
touch library/trainer/LSTM/input/ntm_lstm_input_v_trainer.java
touch library/trainer/LSTM/input/ntm_lstm_input_w_trainer.java
touch library/trainer/LSTM/output/ntm_lstm_output_b_trainer.java
touch library/trainer/LSTM/output/ntm_lstm_output_d_trainer.java
touch library/trainer/LSTM/output/ntm_lstm_output_k_trainer.java
touch library/trainer/LSTM/output/ntm_lstm_output_trainer.java
touch library/trainer/LSTM/output/ntm_lstm_output_u_trainer.java
touch library/trainer/LSTM/output/ntm_lstm_output_v_trainer.java
touch library/trainer/LSTM/output/ntm_lstm_output_w_trainer.java
