cd airfoil_self_noise/sim
source build-riscv.sh
cd ../../airline_passengers/sim
source build-riscv.sh
cd ../../breast_cancer/sim
source build-riscv.sh
cd ../../iris_plant/sim
source build-riscv.sh
cd ../../leukemia/sim
source build-riscv.sh
cd ../../logical_operations/sim
source build-riscv.sh
cd ../../mnist/sim
source build-riscv.sh
cd ../../pima_indians_diabetes/sim
source build-riscv.sh
cd ../../pollution_forecasting/sim
source build-riscv.sh
cd ../../simple_function_regression/sim
source build-riscv.sh
cd ../../simple_pattern_recognition/sim
source build-riscv.sh
cd ../../temperature_forecasting/sim
source build-riscv.sh
cd ../../urinary_inflammations_diagnosis/sim
source build-riscv.sh
cd ../../yacht_hydrodynamics_design/sim
source build-riscv.sh
cd ../../yacht_hydrodynamics_production/sim
source build-riscv.sh
