cd airfoil_self_noise/sim
source build-or1k.sh
cd ../airline_passengers/sim
source build-or1k.sh
cd ../breast_cancer/sim
source build-or1k.sh
cd ../iris_plant/sim
source build-or1k.sh
cd ../leukemia/sim
source build-or1k.sh
cd ../logical_operations/sim
source build-or1k.sh
cd ../mnist/sim
source build-or1k.sh
cd ../pima_indians_diabetes/sim
source build-or1k.sh
cd ../pollution_forecasting/sim
source build-or1k.sh
cd ../simple_function_regression/sim
source build-or1k.sh
cd ../simple_pattern_recognition/sim
source build-or1k.sh
cd ../temperature_forecasting/sim
source build-or1k.sh
cd ../urinary_inflammations_diagnosis/sim
source build-or1k.sh
cd ../yacht_hydrodynamics_design/sim
source build-or1k.sh
cd ../yacht_hydrodynamics_production/sim
source build-or1k.sh
