cd airfoil_self_noise/sim
make clean
cd ../../airline_passengers/sim
make clean
cd ../../breast_cancer/sim
make clean
cd ../../iris_plant/sim
make clean
cd ../../leukemia/sim
make clean
cd ../../logical_operations/sim
make clean
cd ../../mnist/sim
make clean
cd ../../pima_indians_diabetes/sim
make clean
cd ../../pollution_forecasting/sim
make clean
cd ../../simple_function_regression/sim
make clean
cd ../../simple_pattern_recognition/sim
make clean
cd ../../temperature_forecasting/sim
make clean
cd ../../urinary_inflammations_diagnosis/sim
make clean
cd ../../yacht_hydrodynamics_design/sim
make clean
cd ../../yacht_hydrodynamics_production/sim
make clean
